version: "3.8"
services:
  # keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    expose:
        - 8080
    volumes:
        - /etc/timezone:/etc/timezone
        - /etc/localtime:/etc/localtime
    restart: unless-stopped
    user: 1000:1000
    environment:
        # 初始化密码
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=Gcb990217!
        # DB
        - DB_VENDOR=postgres
        - DB_ADDR=postgres12
        - DB_PORT=5432
        - DB_DATABASE=keycloak
        - DB_USER=keycloak
        - DB_PASSWORD=kQSHaDep7U3sTyicgp3lnzdfMI0VWe
        # 开启反向代理
        - PROXY_ADDRESS_FORWARDING=true
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=nginx_all_in_one"
        - "traefik.http.routers.halobug-sso.entrypoints=https"
        - "traefik.http.routers.halobug-sso.tls=true"
        - "traefik.http.routers.halobug-sso.rule=Host(`sso.529777.xyz`)"
        - "traefik.http.services.halobug-sso.loadbalancer.server.scheme=http"
        - "traefik.http.services.halobug-sso.loadbalancer.server.port=8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
        - nginx_all_in_one
networks:
  nginx_all_in_one:
    external: true
