version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2021-09-03T03-56-13Z
    container_name: minio
    restart: unless-stopped
    expose:
      - 9000
      - 9001
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "Gcb990217!"
      MINIO_REGION_NAME: "cn-outline-1"
      MINIO_BROWSER: "on"
      MINIO_SERVER_URL: "https://minio.529777.xyz/"
      MINIO_BROWSER_REDIRECT_URL: "https://minio-admin.529777.xyz/"
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    networks:
      - nginx_all_in_one
networks:
  nginx_all_in_one:
    external: true
